config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users
  resources :reviews
  root "reviews#index"
  post '/stars', :to => 'reviews#star_rating_filter'
  post '/call', :to => 'reviews#callReviews'
  get '/get_reviews', :to => 'reviews#getReviews'
  get '/wordclouds', :to => 'wordclouds#index'
  post '/monkey', :to => 'reviews#monkey'
  get '/search', :to => 'reviews#search'
  post '/shelves', :to => 'shelves#shelves'
  get '/shelves', :to => 'shelves#index'
  get '/welcome', :to => 'reviews#welcome'
  get '/checkCloud', :to => 'reviews#getCloud'
  get '/admin', :to => 'reviews#admin'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :authenticate_user!
	respond_to :html, :xml, :json

  	include ReviewApi
  	include WordCloud
  	include ISBN
  	require 'date'
  	require 'lda-ruby'
  	require 'highscore'
  	require 'fast-stemmer'
  	require 'rake_text'
  	require 'graph-rank'
  	# require 'stanford-core-nlp'
  	require 'ruby_nlp/ngram'
  	require 'ruby_nlp/corpus'
	require 'ruby_nlp/corpus_files/brown'
	require 'matrix'
	require 'tf-idf-similarity'
	require 'monkeylearn'


def index
	  		@review = Review.new
	  		@goodreads_id = session[:isbn].to_s
	  		puts "SESSION ISBN #{@goodreads_id}"
	  		#
	  		@reviews = Review.where("(isbn LIKE '#{@goodreads_id}') AND (who_called LIKE '"+current_user.email+"') AND (review_text LIKE :query OR title LIKE :query)", 
	  		query: "%#{params[:search_reviews]}%")
		  	@img = session[:img]
	  		@title = session[:title]
	  		@author = session[:author]
	  		# @date = session[:date]
	  		@gr_reviews_count = session[:gr_reviews_count]
	  		#run recent titles function
	  		recentTitles
	  		
  	end

  	def recentTitles
  			 #count number of titles pulled this month, using recent titles timestamps
	  		@monthly_titles_pulled = 0
	  		@this_month = Date.today.strftime("%B")
  	#GET RECENT TITLES FOR ALL USERS
	  		@all_users = User.all 
	  		@all_users.each do |user|
	  			@this_month_count = 0
	  			#CHECKING ALL USER TITLE COUNTS FOR ADMIN
	  			if user.recent_titles
		  			user.recent_titles.each do |recent_title|
			  			@pulled_month = recent_title[4].split(" ")[0]
			  			if @pulled_month.to_s == @this_month.to_s
			  				@this_month_count+=1
			  				
			  			end
		  			end
	  			else 
	  				@this_month_count = 0
	  			end
	  			user.recent_titles << @this_month_count 
	  		end
	  		
	  		#GET RECENT TITLES FOR CURRENT USER
	  				  		@current_title_pulled_this_month_check = false
	  		@recent_titles = []
	  		current_user.recent_titles.each do |recent_title|
	  			#check if current title  was pulled this month 
		  		@pulled_month = recent_title[4].split(" ")[0]
		  		if @pulled_month.to_s == @this_month.to_s
			  		@monthly_titles_pulled+=1
			  		if recent_title[0] == session[:isbn]
	  				@current_title_pulled_this_month_check = true
	  				puts @current_title_pulled_this_month_check
	  			end
			  		@recent_titles.push(recent_title)
	  			end
	  		end

			# CHECK TITLE COUNT LIMIT FOR EACH USER
			@monthly_title_max_reached = false
			if current_user.email == "shared@prh.com" && @monthly_titles_pulled >= 3
				@monthly_title_max_reached = true
			end

			if current_user.email == "aslothus@prh.com" && @monthly_titles_pulled >= 200
				@monthly_title_max_reached = true
			end

			if current_user.email == "glevinson@prh.com" && @monthly_titles_pulled >= 50
				@monthly_title_max_reached = true
			end

			if current_user.email == "lkelly@prh.com" && @monthly_titles_pulled >= 30
				@monthly_title_max_reached = true
			end

			if current_user.email == "lcrisp@prh.com" && @monthly_titles_pulled >= 30
				@monthly_title_max_reached = true
			end

			if current_user.email == "dpassannante@prh.com" && @monthly_titles_pulled >= 30
				@monthly_title_max_reached = true
			end
	  		
	  		@monthly_titles_pulled
	  		@recent_titles
	  		#GET RECENTLY PULLED TITLES 
	  			
  		# end
  	end


  	def callReviews
  			#clearing database of reviews called by the current user
			if params[:clearisbn].to_i == 1
				puts "clearing now"
				Review.where(:isbn=>session[:isbn]).where(:who_called=>current_user.email).delete_all
			elsif params[:clearDB].to_i == 1
				Review.delete_all
				Shelf.delete_all
			# check if book has been called recently
			else
				@goodreads_id = session[:isbn].to_s
				api_reviews = ReviewApi::CalledReviews.new

				# ========= GET REVIEWS BY BOOSHAKA CALLS ===========
				@@gr_check = false
				@@amz_check = false
				@gr_review_array = api_reviews.gr_reviews(@goodreads_id)
					if @gr_review_array.length > 1
						@@gr_check = true
					end
				@amz_review_array = api_reviews.amz_reviews(@goodreads_id)
					if @amz_review_array[0] != 1
						@@amz_check = true
					end
				@reviews_array = @gr_review_array.push(*@amz_review_array)
				@reviews_array = @reviews_array.uniq
				# ========= END BOOSHAKA CALL ===========
				
				# ========= GET REVIEWS BY JQUERY, FRONT END =========== 
				# 	platform = params[:call].to_i
				# # get Amazon Reviews
				# if platform == 1
				# 	@reviews_array = api_reviews.amz_reviews(@goodreads_id)
				# 	puts "AMAZON REVIEWS ARRAY #{@reviews_array}"
				# # check if Amazon reviews are ready
				# elsif platform == 1.1
				# 	params[:done=>true]
				# #get goodreads reviews
				# elsif platform == 2
				# 	@reviews_array = api_reviews.gr_reviews(@goodreads_id)
				# #check if amazon reviews are ready
				# elsif platform == 2.2
				# 	@reviews_array = api_reviews.gr_reviews(@goodreads_id)
						
				# end		

				#==========Alternate Goodreads call, calling via NOKOGIRI  ====
				# @gr_reviews_count = session[:gr_reviews_count]
				# puts "SESSION COUNT #{@gr_reviews_count}"
				# @gr_review_array = api_reviews.all_greads_alt_reviews(@goodreads_id, @gr_reviews_count)
				# 	if @gr_review_array.length > 1
				# 		puts "GOODREADS FINISHED"
				# 		@@amz_check = true
				# 		puts "making param #{@@gr_check}"
				# 	end
				# @reviews_array = @gr_review_array
				# # ========= END ALTERNATE CALL ===========

				# ========= COMBINE REVIEWS =========== 

				@reviews_array.each_with_index do |this|
						isbn = this[:isbn]
						rating = this[:rating]
						review_text = this[:review_text].gsub('&#34;', ' ')
						user = this[:user]
						likes = this[:likes]
						platform = this[:platform]
						title = session[:title].to_s		
						date = this[:date].to_s
						img = session[:img]
						author = session[:author]
						whocalled = current_user.email
					@added_review = Review.create(
							isbn: isbn, 
							title: title,
							author: author,
							date: date,
							review_text: review_text,
							platform: platform,
							star_rating: rating, 
							likes: likes,
							who_called: whocalled,
							img: img)
				end
			#UPDATE USER RECENT TITLES
			if current_user
				@title_pulled_this_month = false
				#check if the newly pulled title was pulled already this month
				current_user.recent_titles.each do |title|
					@pulled_month = title[4].split(" ")[0]
					@this_month = Date.today.strftime("%B")
					 if title[0] == @reviews_array[0][:isbn] && @pulled_month.to_s == @this_month.to_s
						@title_pulled_this_month = true
						puts @title_pulled_this_month
					end
				end
				#if the newly pulled title was pulled already this month, don't add
				if @title_pulled_this_month == true
					current_user.save
				else
					#if the newly pulled title wasn't pulled already this month, then add
					current_user.recent_titles << [@reviews_array[0][:isbn], session[:title].to_s, session[:author], session[:img], DateTime.now.strftime("%B %d, %Y"), @reviews_array.length]
					current_user.save
				end
				# if session ISBN is new, then add

			end
		# else
		# 	puts "ALREADY SEARCHED"
		end	
  	 	respond_to do |format|
			format.json { render json: @all_reviews_pass }
			format.js   { render json: @all_reviews_pass }
		end
  	end

  	def getReviews
  	  if @@amz_check == true
  	  		@@amz_check_array = [true]
  	  			respond_to do |format|
					format.json { render :json=> @@amz_check_array }
					format.js   { render :json=> @@amz_check_array }
				end
		end
  	
  end


    def show
  	@review = Review.find(params[:id])
  	end

  	def new
  	@review = Review.new
  	end

  	def create
		@goodreads_id = params[:choice]
		  #get isbn from session if it is blank
		  params[:choice] ||= session[:isbn]
		  #save isbn to session for future requests
		  session[:isbn] = params[:choice]
			session[:img] = params[:img]
			session[:title] = params[:title]
			session[:author] = params[:author]
			session[:gr_reviews_count] = params[:gr_reviews_count]
		redirect_to "/" 
  	end

  	def star_rating_filter
  		#get star filtered reviews text
	  	@user_cloud_prefs = [stars: params[:stars], count: params[:count], cloud_excludes: params[:cloud_excludes], drop_in_text: params[:drop_in_text]]
  		#pass to wordcounter
		new_count = WordCloud::WordCount.new(@user_cloud_prefs)
		@goodreads_id = session[:isbn]
		@top_terms = new_count.get_reviews_by_stars(@goodreads_id)
		# Add total reviews and top terms to array of length 2
		@@arr = []
		@arr2 = []
		#pass through total review count
		@@arr[0] = @top_terms[1]
		# pass through total terms count
		@@arr[1] = @top_terms[2]
		@top_terms[0].each do |key,value|
		  @arr2 << {:text => key, :weight => value[0], :term_star_avg => value[1]}
		end
		@@arr.push(@arr2)
		@@cloud_check = @@arr.to_json
		@@cloud_check = true
		#return to view 
		respond_to do |format|
		  format.json { render json: @@arr }
		  format.js   { render json: @@arr }
		end

  end

   def getCloud
  	  if
  	  		@@cloud_check == true
  	  			respond_to do |format|
					format.json { render :json=> @@arr }
					format.js   { render :json=> @@arr }
				end
		end
  	end

  
  def monkey
  	puts "hitting monkey controller"
  	@goodreads_id = session[:isbn]
  	@reviews_monkey = Review.where("isbn LIKE '%#{@goodreads_id}%'")
  	@all_reviews_array = []
  	@reviews_monkey.each do |review|
		@text = review.review_text.downcase.gsub(/[^0-9a-z ]/i, '').gsub("  ", " ")
		@star = review.star_rating
		@all_reviews_array.push(@text)
	end
	@all_reviews_text = @all_reviews_array.to_sentence
	# EXCLUDE TITLE AND AUTHOR 
	# @exclude_array = [session[:author].split(" ").concat(session[:title].split(" "))]
	@exclude_array = params[:thematic_excludes].downcase.split(' ')
	@title = session[:title].split(' ')
	@author = session[:author].split(' ')
	@exclude_array.push(@title)
	@exclude_array.push(@author)
	@exclude_array = @exclude_array.flatten
	@all_reviews_cleaned_array = @all_reviews_text.split(",")
# LDA EXPERIMENT

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_list.html.erb
<h1>Total Reviews Pulled: <%=@reviews.length%></h1>
<h5> <i>Note: If total is higher than exist on Goodreads and Amazon: 1) Click "Clear Reviews" below 2) Click "Get Amazon/Goodreads reviews" again </i></h4><!-- 

If title count has been reached, and selected title has NOT yet been called, deactivate button -->
<% if @monthly_title_max_reached == true && @current_title_pulled_this_month_check == false%>
<!-- Otherwise, allow repulling of previous title and all new titles -->
<% else %>
	<button id="getGoodreads" class="btn btn-default btn-md">Get Amazon/Goodreads Reviews</button>
	<button id="clearDB" class="btn btn-default btn-md">Clear Reviews for This Title</button>
	<button id="exportReviews" class="export2Excel btn btn-default btn-md">Export to Excel</button>
	<%if current_user && current_user.email == "prhadmin@prh.com"%>
           <button id="clearDBAllUsers" style="background-color:red !important; color:white !important" class="btn btn-default btn-md">CLEAR ENTIRE DATABASE, ALL TITLES</button>
    <%end%>
<% end %>
<table id="summarytable" class="table table-bordered table-hover" data-sort-name="STAR RATING" data-sort-order="desc">
	<thead>
		<tr>
			<th data-sort='string'>BOOK ID</th>
			<th data-sort='string'>TITLE</th>
			<th data-sort='string'>REVIEW TEXT</th>
			<th data-sort='date'>REVIEW DATE</th>
			<th th data-sort='string'>PLATFORM</th>
			<th data-sort='float'>STAR RATING</th>
		</tr>
	</thead>
	<% @reviews.each do |review| %>
	<tbody>
	    <td><%= review.isbn %></td>
	    <td><%= review.title %></td> 		
	    <td class="reviewText"><%= review.review_text %></td>
	    <td> <%= review.date%></td>
	    <td><%= review.platform %></td>
	    <td class="starRating"><%= review.star_rating %></td>
	</tbody>
	<% end %>

</table>

app/views/reviews/_quickDash.html.erb
   

   <div class="container" id="quickDash">

            <!-- <div class="welcome">
                <div>Welcome to the Goodreads/Amazon Reviews Tool. To begin, search for a title along the left-hand navbar by author, keyword, or isbn. Then perform various analysis via the options in the left-hand bar. </div>
               </div> -->
		<div class="row" style="margin-bottom: 30px">
		  <div class="col-md-4 quick_box">
		  	 	<div class="quickDashImage" id="wordcloudquick" value="wordCloudTab">
		 	 		<h5>Word Clouds</h5>
		 		 <img class="demo_img" src="https://i.imgur.com/nMHitSW.png">
		  		</div>
		  </div>
		  <div class="col-md-4 quick_box">
		  	<div class="quickDashImage" id="textAnalysisQuick" value="textual_analysis_tab">
			  	<h5>Textual Analysis</h5>
			  	<img class="demo_img" src="https://i.imgur.com/kH2b3Nv.png">
		  	</div>
		  </div>

		  <div class="col-md-4 quick_box">
		  	<div class="quickDashImage" id="shelvesQuick" value="shelvesTab">
		  		<h5>Goodreads Shelves</h5>
		  	<img class="demo_img" src="https://i.imgur.com/X2Bamdb.png">
		  	</div>
		  </div>
		</div>
   </div>  
 

app/views/reviews/_recentTitles.html.erb
<%if @recent_titles.length < 1%>
	<div>"No previously pulled titles."</div>
<%else%>
	<%@recent_titles.each do |title|%>
			<div class="single_result">
					<div class="cover_result">
						<img src="<%=title[3]%>">
					</div>
					<div class="description_result">
						<p>
						<strong>Title: </strong><%=title[1] %> 
						</p>
						<p>
						<%= button_to "Select this Title", reviews_path, :method => "post", :params => {
						:choice => "#{title[0]}",
						:isbn => "#{title[0]}",
						:img => "#{title[3]}",
						:title =>"#{title[1]}",
						:author => "#{title[2]}"}, class: "btn btn-default btn-md"
						%> 
					</div>
			</div>
			<%end%>
	<%end%>

app/views/reviews/_results.html.erb
<div id="wrapper">
		<div id="page-content-wrapper">
			<%if @result_count == 1%>
				<div class="single_result">
					<div class="cover_result">
						<img src="<%=@returned_books["best_book"]["image_url"]%>">
					</div>
					<div class="description_result">
						<p>
							<strong>Title: </strong><%="#{@returned_books["best_book"]["title"]}" %> |  
							<strong>Author: </strong><%="#{@returned_books["best_book"]["author"]["name"]}" %> 
						</p>
						<p>
							<strong>Goodreads Reviews: </strong><%="#{@returned_books["text_reviews_count"]}" %> | 
							<strong>Avg. Rating: </strong><%="#{@returned_books["average_rating"]}" %> |
							<% @pub_date = "#{@returned_books["original_publication_day"]}/#{@returned_books["original_publication_month"]}/#{@returned_books["original_publication_year"]}" %>
							<strong>Publication Year: </strong><%=@pub_date%>
								<p>
						<%= button_to "Select this Title", reviews_path, :method => "post", :params => {
								:choice => "#{@returned_books["best_book"]["id"]}",
								:img => "#{@returned_books["best_book"]["image_url"]}",
								:title =>"#{@returned_books["best_book"]["title"]}" ,
								:author => "#{@returned_books["best_book"]["author"]["name"]}",
								:date => "#{@pub_date}",
								:gr_reviews_count => "#{@returned_books["text_reviews_count"]}"}, class: "btn btn-default btn-md"
							%> 	
					</div>
				</div>
			<%else%>	
				<%number = 1%>
				<%@result_count.to_i.times do |number| %>
				<div class="single_result">
					<div class="cover_result">
						<img src="<%=@returned_books[number]["best_book"]["image_url"]%>">
					</div>
					<div class="description_result">
						<p>
							<strong>Title: </strong><%="#{@returned_books[number]["best_book"]["title"]}" %> |  
							<strong>Author: </strong><%="#{@returned_books[number]["best_book"]["author"]["name"]}" %> 
						</p>
						<p>
							<strong>Reviews: </strong><%="#{@returned_books[number]["text_reviews_count"]}" %> | 
							<strong>Avg. Rating: </strong><%="#{@returned_books[number]["average_rating"]}" %> |
							<% @pub_date = "#{@returned_books[number]["original_publication_day"]}/#{@returned_books[number]["original_publication_month"]}/#{@returned_books[number]["original_publication_year"]}" %>
							<strong>Publication Year: </strong><%=@pub_date%>
								<p>
						<%= button_to "Select this Title", reviews_path, :method => "post", :params => {
								:choice => "#{@returned_books[number]["best_book"]["id"]}",
								:img => "#{@returned_books[number]["best_book"]["image_url"]}",
								:title =>"#{@returned_books[number]["best_book"]["title"]}" ,
								:author => "#{@returned_books[number]["best_book"]["author"]["name"]}",
								:date => "#{@pub_date}",
								:gr_reviews_count => "#{@returned_books[number]["text_reviews_count"]}"}, class: "btn btn-default btn-md"
							%> 	
					</div>
					</div>
					<%end%>
				</div>
			<%end%>
		</div>
	</form>
</div>

app/views/reviews/_sidebar.html.erb
      <div role="tabpanel" aria-labelledby="Recent Titles" class="tab-pane fade in " id="recent_titles">
          <h1>RECENT TITLES</h1>
            <%@recent_titles = recent_titles %>
            <%= render 'recentTitles', :recent_titles => @recent_titles%>
        </div>

<!--         <div role="tabpanel" aria-labelledby="My Lists" class="tab-pane fade in " id="my_lists">
            <h1>MY LISTS </h1>
            <%=@my_lists%>
        </div> -->
        <div role="tabpanel" aria-labelledby="Textual Analysis" class="tab-pane fade in " id="textualAnalysisPanel">
            <h1>Textual Analysis: Multi-term Phrases</h1>
            <h4>Note: "Diff from Avg" is the difference between the average star rating for the book and the average star rating of reviews that contain the given phrase.</h4>
            <div id="textAnalysisBox">
             <!--  <div class="text_analysis" id="named_entity">
                      <p><button id="npl_entity">Named-Entity Recognition</button>
                      </p>
                  <div class="entity_results"></div>
                  </div> -->
<!--               <div class="text_analysis">
                <button id="npl_adj">Adjectives</button>
              </div> -->
                <div class="text_analysis" id="ngrams">
                  <div class="spinnerBox" id="ngram_spinner">
                      <i class="fa fa-spinner fa-pulse fa-3x fa-fw margin-bottom" ></i>
                  </div>
                    <div id="ngram_submit_container">
                      <button id="npl_ngram" class="btn btn-default btn-md">Analyze 2-6 Term Ngrams</button>
                      <input id="ngramDropIn" placeholder="Or drop-in any text to analyze"></input>
                </div>
              </div>
            </div>
        </div>
        <div role="tabpanel" aria-labelledby="wordCloudTab" class="tab-pane fade" id="wordCloudPanel">
            <div class="summaryOverlay">
                  <div class="spinnerBox" id="cloud_spinner">
                      <div class="apiProgress" id="cloudNotify">Fluffing that cloud...</div>
                      <i class="fa fa-spinner fa-pulse fa-3x fa-fw margin-bottom" ></i>
                  </div>
                </div>
            <div class="btn-group" data-toggle="buttons-checkbox">
              <h1>Reviews Word Clouds</h1>
              <button type="button" id="sb1" class="btn btn-default btn-md">
                  <span class="glyphicon glyphicon-star" aria-hidden="true"></span> 1 Star
              </button>
              <button type="button" id="sb2" class="btn btn-default btn-md">
                  <span class="glyphicon glyphicon-star" aria-hidden="true"></span> 2 Star
              </button>
              <button type="button" id="sb3" class="btn btn-default btn-md">
                  <span class="glyphicon glyphicon-star" aria-hidden="true"></span> 3 Star
              </button>
              <button type="button" id="sb4" class="btn btn-default btn-md">
                  <span class="glyphicon glyphicon-star" aria-hidden="true"></span> 4 Star
              </button>
              <button type="button" id="sb5" class="btn btn-default btn-md">
                  <span class="glyphicon glyphicon-star" aria-hidden="true"></span> 5 Star
              </button>
              <button type="submit" id="starSubmit" class="btn btn-default btn-md"> Make a cloud! 
              </button>
            </div>
            <div class="cloudParams">
              <p>Exclude words (space separated): <input type="text" name="fname" id="user_excludes" value="read star book author review"></p>
              <p>Minimum word frequency: <input type="text" name="fname" id="count_limit" value="50"></p>
              <form>
                <p>Drop-in Text? <input type="text" name="fname" id="drop_in_text" value="" maxlength="10000000000000000000000"> (Generate a wordcloud from any text you provide, instead of this title's reviews.)
                </p>

              <form>
                <input type="checkbox" id="authorCheck" name="vehicle" value="Bike">  Exclude author and title?<br>
              </form>
            </div>
              <div class="wordCloudsBox">
              </div>
          </div>
          <div role="tabpanel" aria-labelledby="themesTab" class="tab-pane fade" id="themes">
            <div id="monkey_themes">
            </div>
            <div id="monkey_keywords">
              <h1>MonkeyLearn's Keyword Analysis</h1>
              <canvas id="keywordsChart" width="1000px" height="600px"></canvas>
              <div class="spinnerBox" id="monkey_spinner">
                <i class="fa fa-spinner fa-pulse fa-3x fa-fw margin-bottom" ></i>
              </div>
            </div>
          </div>
          <div role="tabpanel" aria-labelledby="shelvesTab" class="tab-pane fade" id="shelves">
          <h1>Goodreads Shelves</h1>
          <h4><i>Goodreads “shelves” are user-generated tags for titles (eg. “fiction”, “book club book”, etc.).  The following keyword-based roll-ups of Goodreads shelves provide insight into the categories where Goodreads users have shelved the given title most often. Reading status shelves have been omitted (eg. “to read”).</i></h4>
          <div class="ngram_call_container">
            <button id="shelvesCall" class="btn btn-default btn-md">Get Goodreads Shelves</button>
            <div id="ngramerrorbox"> <---- Woops, please try that again.</div>
          </div>
              <div id="shelves_chart_box" class=".container-fluid">
                  <h1>Goodreads Shelves - Category Roll-Ups</h1>
                  <h4 id="shelves_total_box"></h4>
                  <div id="rolled_shelves"> 
                     <canvas id="rollShelvesChart" class="shelvesChart" width="900px" height="600px"></canvas>
                     <div class="spinnerBox">
                        <i class="fa fa-spinner fa-pulse fa-3x fa-fw margin-bottom" ></i>
                      </div>
                  </div>
                <h1>Goodreads Shelves - All Shelves</h1>
                 <div id="all_shelves">
                    <canvas id="allShelvesChart" class="shelvesChart" width="900px" height="600px"></canvas>
                     <div class="spinnerBox">
                        <i class="fa fa-spinner fa-pulse fa-3x fa-fw margin-bottom" ></i>
                      </div>
                  </div>
              <div class="col-sm-4">
                    <h2>Category Roll-Ups</h2>
                    <table id="rolled_shelves_table"class="table table-bordered table-hover shelves_table" data-sort-name="val" data-sort-order="desc">
                        <thead>
                          <tr>
                            <th data-sortable="true">Shelf Name</th>
                            <th data-sortable="true">Count</th>
                          </tr>
                        </thead>
                    </table>
                </div>
                <div class="col-sm-4">
                    <h2>All Shelves</h2>
                    <table id="all_shelves_table" class="table table-bordered table-hover shelves_table" data-sort-name="val" data-sort-order="desc">
                        <thead>
                          <tr>
                            <th data-sortable="true">Shelf Name</th>
                            <th data-sortable="true">Count</th>
                          </tr>
                        </thead>
                    </table>
                </div>
                <div class="col-sm-4">
                  <div class="btn-group" data-toggle="buttons-checkbox">
                        <h2>Add New Category</h1>
                        <input class="addCustomCategory" id="CatName" placeholder="Category Name"></input>
                        <input class="addCustomCategory" id="CatTerm1" placeholder="Category Term 1"></input>
                        <input class="addCustomCategory" id="CatTerm1" placeholder="Category Term 2"></input>
                        <button type="submit" id="starSubmit" class="btn btn-default btn-md">Submit
                        </button>
                      </div>
                  <form id="customShelvesCategory"></input>
                </div>
              </div>
            </div>
          </div>
        </div>
          </div>
          <!-- /#page-content-wrapper -->
    </div>

app/views/reviews/create.html.erb
CREATE 

<h1><%= @review %></h1>

app/views/reviews/edit.html.erb
EDIT

app/views/reviews/index.csv.erb
<%- headers = ['Title', 'Review'] -%>
<%= CSV.generate_line headers %>
<%- @reviews.each do |review| -%>
  <%= CSV.generate_line([review.title, review.review_text]) %>
<%- end -%>

app/views/reviews/search.html.erb
<%= render 'results'%>
      

app/views/reviews/show.html.erb
SHOW

app/views/reviews/welcome.html.erb
<div id="wrapper">
	<div id="page-content-wrapper">
		<div class="welcomeBox">
			<h1>Welcome to the Goodreads/Amazon Reviews Tool</h1>
			<h2>To begin, search for a title along the left-hand navbar by author, keyword, or isbn.</h2>
			<h2>Then perform various analysis via the options in the left-hand bar.</h2>
		 </div>
		 <i class="fa fa-arrow-up fa-3x fa-rotate-90 blink_me fa-inverse"></i>
	</div>
</div>